server:
  port: 8081 # Port nội bộ của Auth Service

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Cấu hình Secret Key cho JWT (Phải đủ dài, ít nhất 256-bit)
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}